### ISSUE TITLE
Finalize the harvest cost function

### ISSUE THREAD

**Issue by mspringborn** [mspringborn/salmonids#2]
In May I altered the harvest cost function so that harvest cost would be decreasing in stock.  The version I used was a quick fix.  We should find a standard function that has the desired property (harvest cost decreasing in stock) e.g. maybe from Conrad and Clark. The current function might be fairly standard--just need to verify.

**Comment by mspringborn** [comment]
Amanda, here's what I'd like to use as the cost function.  C/S is a common marginal cost function, that increases as the stock declines, where C is just some parameter.  C*ln(S/A) is derived from integrating that simple cost function over the appropriate domain (as in the image).  Will you switch out the cost function, tuning C (feel free to rename) so that costs change as little as possible from the current form?  Thanks, M

![20150610_151217](https://cloud.githubusercontent.com/assets/12819222/8142031/5f61d3a8-1125-11e5-8653-61319fb15270.jpg)

**Comment by amandafaig** [comment]
done.  I've edited all 3 files that contain a pi function, since I haven't removed the redundancy yet.

**Comment by mspringborn** [comment]
This didn't get implemented cleanly because I used A for escapement in raw units above, while in our code escapement is a share, [0,1].  So if A is in [0,1], then the function above should be: c*ln(S/(A*S)) = c*ln(1/A).  The funny thing is, this is independent of the stock: the cost only depends on what proportion of the stock you intend to take (1-A) or leave (A).

Image below at various stocks given by c=100*.075.

![image](https://cloud.githubusercontent.com/assets/12819222/8342067/72a02d5e-1a7e-11e5-9b1f-d8d0259be604.png)

**Comment by amandafaig** [comment]
Oh, yeah, I assumed it was the escapement measure we were already using.

It’s been changed to 1/A (instead of S/A).

-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
Amanda, please change the cost portion of the profit function to: 

c*log(1./A)

where c is equal to something like 7.5 (i.e. 100 times the current level of c, 0.075, which was specified for an earlier form.  Let's get rid of the old functional forms for profit here.

**Comment by amandafaig** [comment]
Ok, changed c=7.5

FYI, all of this is done in sc_setup.. in case if you want to tinker with c at some later point.


-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
**" Let's get rid of the old functional forms for profit here."

**Comment by amandafaig** [comment]
Ok, sorry I missed that.
This is in all of the older programs (VFI through offgrid FDP), found in sc_setup:
![screen shot 2015-06-24 at 4 44 17 pm](https://cloud.githubusercontent.com/assets/7494361/8343995/5f4ca6f8-1a90-11e5-97f2-c2a4c7e9ef3a.png)

and this is in the new, functionalized version (in nextperiodfunction):
![screen shot 2015-06-24 at 4 44 47 pm](https://cloud.githubusercontent.com/assets/7494361/8344000/68c438b8-1a90-11e5-9de0-f63010fced0d.png)

**Comment by mspringborn** [comment]
cool
