### ISSUE TITLE
update code so macs can talk to R as well

### ISSUE THREAD

**Issue by amandafaig** [mspringborn/salmonids#5]
Right now we've got great code for Matlab on PCs to talk to R, but as far as I can tell it doesn't work for Macs.

**Comment by amandafaig** [comment]
Ok... so I got this working, but for some reason it doesn't work well--I get a lot of failed runs (i.e. I see the error "this should never happen" a lot, because both of the possible nonparametric regression models timed out) 

I'm going to keep tinkering on this for a little bit tonight to see if I can figure out what's up.

Note, in order to do this I had to add one more variable up top.  I've called it DOS for now... DOS = 1 means you're using DOS... DOS = 0 means you're using linux or mac.

**Comment by mspringborn** [comment]
Use this matlab command to automate: 
str = computer; 

See documentation on "computer" command to differentiate systems.

**Comment by amandafaig** [comment]
cool, will do

**Comment by amandafaig** [comment]
Ok, great.  It's working really well.  This is on the 'old' or non-funcionalized version.

![screen shot 2015-06-26 at 5 37 14 pm](https://cloud.githubusercontent.com/assets/7494361/8389678/5d954c3e-1c2a-11e5-9ae0-e50987e711cf.png)
