### ISSUE TITLE
Edit offgrid_FDP_function to have graphs for 3D+

### ISSUE THREAD

**Issue by amandafaig** [mspringborn/salmonids#8]

**Comment by amandafaig** [comment]
What I ended up doing, rather than have a switch/case that went on and on and on, is I simply made it so the user decides what is plotted.  This is done in FDP_main_script, around line 126-143:

![screen shot 2015-07-02 at 6 05 47 pm](https://cloud.githubusercontent.com/assets/7494361/8490867/fdc6172e-20e4-11e5-8ab1-191dae82a6c9.png)

Do you think it would be useful to have the option to plot from multiple angles?  It's not hard to code, it just makes the main script a little messier.

**Comment by mspringborn** [comment]
I wouldn't spend too much time in plotting now. It'll just depend on what's most informative for following the solution.

Mike Springborn
UC Davis
http://springborn.faculty.ucdavis.edu/



-----Original Message-----

**Comment by amandafaig** [comment]
Ok, sounds good.  Then this issue is closed!  I'm working on the policy function now, and waiting to hear back from Allison regarding moving to a % or number of individuals-based management (versus intensity).  

Since those are the last two issues, we might want to talk about what to do next.  I assume 2 reach, 1 control is next, and then 2 reach 2 control, etc... I'm happy to talk tomorrow, the weekend, or next week--just say when.
