### ISSUE TITLE
Edit offgrid_FDP_function to produce policy function

### ISSUE THREAD

**Issue by amandafaig** [mspringborn/salmonids#9]

**Comment by amandafaig** [comment]
Hi Mike,

Can I check this with you?

In a post decision state framework, in the case where the shock is uncorrelated through time, the policy function is still a function of the shock, right?  

i.e. The policy at time {t} will depend on both the shock and stock at time {t}, even though V(s_{t},z_{t-1}) = V(s_{t}) since z_{t} and z_{t-1} are uncorrelated.

i.e. When shock is autocorrelated the state space over which the value function is defined (s_{t},z_{t-1}) is the same size as the state space over which the policy function is defined (s_{t},z_{t}).   When shock is uncorrelated over time, the state space over which the value function is defined (s_{t}) is smaller than the space over which the policy function is defined (s_{t},z_{t}).

i.e. The plots should look something like this, assuming only one stock and one shock:
<img width="736" alt="policy_uncorr_vs_corr p26" src="https://cloud.githubusercontent.com/assets/7494361/8509623/31123e4a-2262-11e5-9dc5-1b73910c5912.png">


correct, or disagree?

**Comment by mspringborn** [comment]
Good questions.
“In a post decision state framework, in the case where the shock is uncorrelated through time, the policy function is still a function of the shock, right?”
-->Yes and no.  The policy function would be a function of (st,zt) but it would be simpler just to characterize it as a univariate function of the post shock state, e.g. st’.  Once zt is accounted for to arrive at st’, it’s value no longer matters.

**Comment by amandafaig** [comment]
Makes sense !

sent from my phone

**Comment by amandafaig** [comment]
I've included policy function output in the functionalized version.  I'm not bothering to include it in the salmon_offgrid_FDP version since really we should be moving away from that now that the functionalized version is working.

![screen shot 2015-07-06 at 2 38 30 pm](https://cloud.githubusercontent.com/assets/7494361/8534013/8e52025c-23ed-11e5-8628-7be57eb40a9d.png)
The above is for the simple fisheries problem.
